dataset:
  name: agnews
  path: /root/autodl-tmp/prompt/EmoryNLP/
#  path: /root/autodl-tmp/prompt/MELD/
task: classification
classification:
    parent_config: task
    metric:
        - micro-f1
    loss_function: cross_entropy ## select from cross_entropy

plm:
  model_name: roberta
  model_path: "ERCroberta"
#  model_path: "ERCroberta_MELD"
  optimize:
    freeze_para: False
    lr: 0.00001
    weight_decay: 0.01
    scheduler:
      type:
      num_warmup_steps: 500
train:
  num_epochs: 8
  batch_size: 12

test:
  batch_size: 8

dev:
  batch_size: 8

logging:
  pathbase: /root/prompt/logging


template: manual_template
verbalizer: manual_verbalizer

manual_template:
  choice: 0
  file_path: /root/autodl-tmp/Step2 prompt/scripts/ERC_template.txt


manual_verbalizer:
  choice: 0
  file_path: /root/autodl-tmp/Step2 prompt/scripts/ERC_EmoryNLP_verbalizer.txt
#  file_path: /root/autodl-tmp/prompt/scripts/ERC_MELD_template.txt  
environment:
  num_gpus: 1
  cuda_visible_devices:
  local_rank: 0

learning_setting: full

#few_shot:
#  parent_config: learning_setting
#  few_shot_sampling: sampling_from_train

#sampling_from_train:
#  parent_config: few_shot_sampling
#  num_examples_per_label: 10
#  also_sample_dev: True
#  num_examples_per_label_dev: 10
#  seed:
#    - 123
#    - 456
#    - 789
#    - 321
#    - 654
